name: Update Blogs

on: workflow_dispatch

jobs:
  update_blogs:
    runs-on: ubuntu-latest
    name: Update Blog File
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   ref: amajhi/update-file-action
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd ./action
          npm install
          npm run build
          npm start