name: Update Blogs

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    runs-on: ubuntu-latest
    name: Update Blog File
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Latest Hashnode Posts
        id: latest_hashnode_posts
        uses: anupammajhi/githubaction-latest-hashnode-posts@v1.0.0
        with:
          HASHNODE_PUBLICATION_ID: ${{ secrets.ANUPAMMAJHI_HASHNODE_PUB_ID }}
      - name: Install node20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update File
        id: update_file
        uses: anupammajhi/githubaction-update-repo-file@vtest
        with:
          FILE_PATH: "blogs.html"
          STARTING_COMMENT: "<!-- BLOG_AUTO_START -->"
          ENDING_COMMENT: "<!-- BLOG_AUTO_END -->"
          EJS_TEMPLATE_PATH: "action/src/blogTemplate.ejs"
          TEMPLATE_INPUT_JSON: ${{steps.latest_hashnode_posts.outputs.result}}
          